"""Migration for adding the sort reference field to the Paint model."""
# Generated by Django 5.1 on 2024-08-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration for adding the sort reference field to the Paint model."""

    dependencies = [
        ("paint_manager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paint",
            name="sort_reference",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=200,
                verbose_name="référence",
            ),
        ),
    ]
