services:
  sql_database:
    image: postgres:alpine
    volumes:
    - .docker/postgresql:/var/lib/postgresql/data
    healthcheck:
      test: [CMD, pg_isready, -U, u_df_site, -d, d_df_site]
      interval: 10s
      timeout: 5s
      retries: 10
    environment:
    - PGDATA=/var/lib/postgresql/data/postgresql
    - POSTGRES_DB=d_df_site
    - POSTGRES_PASSWORD=p_df_site
    - POSTGRES_USER=u_df_site
    ports:
    - 127.0.0.1:5432:5432
    restart: always
  redis_database:
    image: redis:alpine
    volumes:
    - .docker/redis:/data
    command: redis-server --requirepass "p_df_site"
    environment:
    - REDIS_PASSWORD=p_df_site
    ports:
    - 127.0.0.1:6379:6379
    healthcheck:
      test: [CMD, redis-cli, ping]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: always
  minio_storage:
    image: minio/minio:latest
    volumes:
    - .docker/minio:/data
    environment:
    - MINIO_ROOT_USER=u_df_site
    - MINIO_ROOT_PASSWORD=p_df_site
    command: server --address 0.0.0.0:9000 --console-address 0.0.0.0:9001 --compat /data
    ports:
    - 127.0.0.1:9000:9000
    - 127.0.0.1:9001:9001
    healthcheck:
      interval: 60s
      retries: 10
      test: [CMD, mc, ready, local]
      timeout: 5s
    restart: always
  prometheus:
    image: prom/prometheus
    volumes:
    - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
    - 127.0.0.1:9090:9090
