# Generated by Django 5.0.7 on 2024-08-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("modersite", "0002_preferencesuser_email_notifications"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertRibbon",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("success", "Success"),
                            ("warning", "Warning"),
                            ("danger", "Danger"),
                            ("primary", "Primary"),
                            ("secondary", "Secondary"),
                            ("dark", "Dark"),
                            ("light", "Light"),
                            ("tricolor", "Tricolor"),
                        ],
                        db_index=True,
                        default="info",
                        max_length=10,
                        verbose_name="Color",
                    ),
                ),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "start_date",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Start date"),
                ),
                (
                    "end_date",
                    models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="End date"),
                ),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True, verbose_name="Is active"),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name="Position"),
                ),
            ],
            options={
                "verbose_name": "Alert ribbon",
                "verbose_name_plural": "Alert ribbons",
                "ordering": ("-start_date",),
            },
        ),
    ]
