# Generated by Django 5.0.7 on 2024-08-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("modersite", "0003_alertribbon"),
    ]

    operations = [
        migrations.AddField(
            model_name="alertribbon",
            name="resume",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Resume"),
        ),
        migrations.AddField(
            model_name="alertribbon",
            name="url",
            field=models.URLField(blank=True, null=True, verbose_name="URL"),
        ),
    ]
