# Generated by Django 5.0.7 on 2024-08-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("modersite", "0004_alertribbon_resume_alertribbon_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alertribbon",
            name="resume",
        ),
        migrations.AddField(
            model_name="alertribbon",
            name="summary",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Summary"),
        ),
    ]
